/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Albert Gregl (https://sketchfab.com/AlbertGregl)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rubber-duck-7eb15f3c897049f8ba35f8f56f081dff
Title: Rubber Duck
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import {useFrame, useThree} from "@react-three/fiber";

const Duck = (props) => {
    const { nodes, materials } = useGLTF("/rubber_duck.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.RubberDuck}
                position={[0, 0.583, 0]}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    );
}

useGLTF.preload("/rubber_duck.glb");

export default Duck;